apiVersion: v1
kind: Template
metadata:
  annotations:
    description: The spring-music application
    tags: spring-music
  name: spring-music
parameters:
  - name: APP_NAME
    value: spring-music
    description: The name of the application
    required: true
  - name: GIT_URL
    value: "https://github.com/edeandrea/summit-lab-spring-music.git"
    description: The git url to build from
    required: true
  - name: GIT_REF
    value: pipeline
    description: The git branch/tag to pull from
    required: true
objects:
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      labels:
        app: ${APP_NAME}
      name: default_view
    roleRef:
      name: view
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
    subjects:
      - kind: ServiceAccount
        name: default
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      tags:
        - name: latest
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      runPolicy: Serial
      source:
        type: Git
        contextDir: /
        git:
          ref: ${GIT_REF}
          uri: ${GIT_URL}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: "java:11"
            namespace: openshift
      output:
        to:
          kind: ImageStreamTag
          name: "${APP_NAME}:latest"
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      labels:
        build: ${APP_NAME}-${GIT_REF}-git
      name: ${APP_NAME}-${GIT_REF}-git
    spec:
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: ${GIT_URL}
          ref: ${GIT_REF}
      strategy:
        type: JenkinsPipeline
        jenkinsPipelineStrategy:
          jenkinsfilePath: Jenkinsfile
          env:
            - name: NEXUS_URL
              value: "http://nexus.labs-infra.svc:8081"
      triggers:
        - type: ConfigChange
        - type: GitHub
          github:
            secret: lNW-G9fDOk--MYJ3iNK1
        - type: Generic
          generic:
            secret: ZSyQC2Cy7nc6fMxZJMZi
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      labels:
        build: image-quay-image-mover
      name: image-quay-image-mover
    spec:
      runPolicy: Serial
      output:
        pushSecret:
          name: quay
        to:
          kind: DockerImage
          name: "quay.io/edeandrea/${APP_NAME}:latest"
      source:
        type: Dockerfile
        dockerfile: "FROM ${APP_NAME}:latest"
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: ${APP_NAME}:latest
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
        app.openshift.io/runtime: spring
        app.openshift.io/runtime-version: '8'
      name: ${APP_NAME}
      annotations:
        app.openshift.io/vcs-ref: ${GIT_REF}
        app.openshift.io/vcs-uri: ${GIT_URL}
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${APP_NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}
            deploymentconfig: ${APP_NAME}
        spec:
          containers:
            - image: ${APP_NAME}:latest
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /actuator/health/liveness
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 10
              name: ${APP_NAME}
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8443
                  protocol: TCP
                - containerPort: 8778
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /actuator/health/readiness
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 10
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_NAME}
            from:
              kind: ImageStreamTag
              name: ${APP_NAME}:latest
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: 8443-tcp
          port: 8443
          protocol: TCP
          targetPort: 8443
        - name: 8778-tcp
          port: 8778
          protocol: TCP
          targetPort: 8778
      selector:
        deploymentconfig: ${APP_NAME}
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${APP_NAME}
        weight: 100
