apiVersion: v1
kind: Template
metadata:
  name: summit-lab-spring-music-db
parameters:
  - name: DATABASE_NAME
    value: music
    description: The name of the database to use
    required: true
  - name: DATABASE_USERNAME
    generate: expression
    from: "[a-zA-Z]{32}"
    description: The database username
  - name: DATABASE_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    description: The database password
  - name: DATABASE_DEBEZIUM_USERNAME
    value: dbz
    generate: expression
    from: "[a-zA-Z]{32}"
    description: The database username for Debezium
  - name: DATABASE_DEBEZIUM_PASSWORD
    value: debezium
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    description: The database password for Debezium
  - name: DATABASE_ADMIN_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    description: The database admin password
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: summit-lab-spring-music-db
      labels:
        application: summit-lab-spring-music
      annotations:
        template.openshift.io/expose-database_name: '{.data[''database-name'']}'
        template.openshift.io/expose-password: '{.data[''database-password'']}'
        template.openshift.io/expose-username: '{.data[''database-user'']}'
        template.openshift.io/expose-admin_password: '{.data["database-admin-password"]}'
    stringData:
      database-name: ${DATABASE_NAME}
      database-password: ${DATABASE_PASSWORD}
      database-user: ${DATABASE_USERNAME}
      database-admin-password: ${DATABASE_ADMIN_PASSWORD}
  - kind: Secret
    apiVersion: v1
    metadata:
      name: summit-lab-spring-music-db-connector-creds
      labels:
        app: spring-music-cdc
    type: Opaque
    stringData:
      connector.properties: |-
        dbUsername: ${DATABASE_DEBEZIUM_USERNAME}
        dbPassword: ${DATABASE_DEBEZIUM_PASSWORD}
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: summit-lab-spring-music-db-init-config
      labels:
        application: summit-lab-spring-music
        app: summit-lab-spring-music
    data:
      initdb.sql: |-
        CREATE USER IF NOT EXISTS '${DATABASE_DEBEZIUM_USERNAME}'@'%' IDENTIFIED WITH mysql_native_password BY '${DATABASE_DEBEZIUM_PASSWORD}';
        GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO '${DATABASE_DEBEZIUM_USERNAME}'@'%';
        FLUSH PRIVILEGES;
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: summit-lab-spring-music-db-config
      labels:
        application: summit-lab-spring-music
        app: summit-lab-spring-music
    data:
      my-debezium.cnf: |-
        !include /etc/my.cnf

        [mysqld]
        server-id = 223344
        server_id = 223344
        log_bin = ON
        binlog_format = ROW
        binlog_row_image = full
        binlog_rows_query_log_events = ON
        expire_logs_days = 10
        gtid_mode = ON
        enforce_gtid_consistency = ON
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: summit-lab-spring-music-db
      labels:
        application: summit-lab-spring-music
        app: spring-music
        app.kubernetes.io/part-of: spring-music
        app.openshift.io/runtime: mysql
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
    spec:
      replicas: 1
      strategy:
        type: Recreate
        recreateParams:
          post:
            failurePolicy: Abort
            execNewPod:
              command:
                - /bin/sh
                - '-c'
                - sleep 10 && MYSQL_PWD="$MYSQL_ROOT_PASSWORD" $MYSQL_PREFIX/bin/mysql -h $SUMMIT_LAB_SPRING_MUSIC_DB_SERVICE_HOST -u root < /entrypoint/initdb.d/initdb.sql
              containerName: summit-lab-spring-music-db
              volumes:
                - summit-lab-spring-music-db-init
      selector:
        name: summit-lab-spring-music-db
      template:
        metadata:
          name: summit-lab-spring-music-db
          labels:
            name: summit-lab-spring-music-db
        spec:
          volumes:
            - name: db-data
              emptyDir: {}
            - name: summit-lab-spring-music-db-init
              configMap:
                name: summit-lab-spring-music-db-init-config
            - name: summit-lab-spring-music-db-config
              configMap:
                name: summit-lab-spring-music-db-config
          containers:
            - env:
                - name: MYSQL_DEFAULTS_FILE
                  value: /entrypoint/configdb.d/my-debezium.cnf
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: summit-lab-spring-music-db
                      key: database-user
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: summit-lab-spring-music-db
                      key: database-password
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: summit-lab-spring-music-db
                      key: database-name
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: summit-lab-spring-music-db
                      key: database-admin-password
              name: summit-lab-spring-music-db
              image: ' '
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: db-data
                  mountPath: /var/lib/mysql/data
                - name: summit-lab-spring-music-db-init
                  mountPath: /entrypoint/initdb.d
                - name: summit-lab-spring-music-db-config
                  mountPath: /entrypoint/configdb.d
              ports:
#                - containerPort: 5432
                - containerPort: 3306
                  protocol: TCP
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 3306
#                exec:
#                  command:
#                    - /bin/sh
#                    - -i
#                    - -c
#                    - mysqladmin -u$MYSQL_USER -p$MYSQL_PASSWORD -h 127.0.0.1 ping
##                    - pg_isready -h 127.0.0.1 -p 5432
                timeoutSeconds: 1
              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - -i
                    - -c
                    - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE -e 'SELECT 1'
#                    - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 512Mi
              securityContext:
                privileged: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - summit-lab-spring-music-db
            from:
              kind: ImageStreamTag
              name: mysql:8.0
              namespace: openshift
            lastTriggeredImage: ""
  - kind: Service
    apiVersion: v1
    metadata:
      name: summit-lab-spring-music-db
      labels:
        application: summit-lab-spring-music
        app: summit-lab-spring-music
      annotations:
        template.openshift.io/expose-uri: mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}
    spec:
      ports:
        - name: mysql
          port: 3306
          protocol: TCP
          targetPort: 3306
#        - name: postgres
#          port: 5432
#          protocol: TCP
#          targetPort: 5432
      selector:
        name: summit-lab-spring-music-db
