name: Basic build and test

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
    branches:
      - pipeline

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - pipeline
    paths-ignore:
      - "**/*.md"
      - ".github/dependabot.yml"

  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  jvm-build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - '17'
          - '21'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
          cache: maven

      - name: "Build and test JVM ${{ matrix.java }}"
        run: ./mvnw -B clean verify -Dmaven.compiler.release=${{ matrix.java }}
