name: Basic build and test

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
    branches:
      - pipeline

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - pipeline
    paths-ignore:
      - "**/*.md"
      - ".github/dependabot.yml"

  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  jvm-build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - '17'
          - '21'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
          cache: maven

      - name: "Build and test JVM ${{ matrix.java }}"
        run: ./mvnw -B clean verify -Dmaven.compiler.release=${{ matrix.java }}

  native-build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        graal:
          - { graal: '21.0.1', java: '21' }
          - { graal: '17.0.9', java: '17' }
    steps:
      - uses: actions/checkout@v4

      - name: Cache and restore GraalVM CE (${{ matrix.graal.graal }})
        id: check-graal-cache
        uses: actions/cache@v3
        with:
          path: graalvm-community-jdk-${{ matrix.graal.graal }}_linux-x64_bin.tar.gz
          key: graal-distro-${{ matrix.graal.graal }}

      - name: Download GraalVM CE ${{ matrix.graal.graal }}
        if: steps.check-graal-cache.outputs.cache-hit != 'true'
        run: |
          download_url="https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-${{ matrix.graal.graal }}/graalvm-community-jdk-${{ matrix.graal.graal }}_linux-x64_bin.tar.gz"
          wget -q -O graalvm-community-jdk-${{ matrix.graal.graal }}_linux-x64_bin.tar.gz $download_url

      - name: Setup GraalVM CE ${{ matrix.graal.graal }} distro
        uses: actions/setup-java@v3
        with:
          distribution: 'jdkfile'
          jdkFile: graalvm-community-jdk-${{ matrix.graal.graal }}_linux-x64_bin.tar.gz
          java-version: ${{ matrix.graal.java }}
          architecture: x64
          cache: maven

      - name: Build test native (${{ matrix.graal.graal }})
        run: ./mvnw -B clean verify -PnativeTest -Dmaven.compiler.release=${{ matrix.graal.java }}
